# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
	. ~/.bashrc
fi

# User specific environment and startup programs
# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
alias kubectl=kubecolor
alias k=kubectl
complete -o default -F __start_kubectl k

alias pls='sudo !!' # Because we all forget sudo
alias cat='bat'
alias ls='eza -lah --git'

# PROMPT_COMMAND='history -a'

eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)


 default -F __start_kubectl k
# autocomplete kind
. <(kind completion bash)

export PS1='\[\033]133;D;$?\]\[\033\\\033]133;A\033\\\][\u@\h \W]\$ \[\033]9;9;"$(wslpath -w "${PWD}")"\033\\\]\[\033]133;B\033\\\]'

eval "$(starship init bash)"
export PATH=/home/egarciad/local/bin:$PATH
